"""
Example test script.

This is a complete, working example that can be run as part of the test suite. It does a
simple test of a relativistic shock tube using the GR framework. There are many comments
in order to make this file self-explanatory, but the actual working code is only 28
lines long.

There are three functions defined here:
    prepare(**kwargs)
    run(**kwargs)
    analyze()
All three must be defined with the same names and no required inputs in order to make a
working script. They are called in sequence from the main test script run_tests.py.
Additional support functions can be defined here, to be called by the three primary fns.

Heavy use is made of support utilities defined in scripts/utils/athena.py. These are
general-purpose Python scripts that interact with Athena++. They should be used whenever
possible, since they work together to compile and run Athena++ and read the output data.
In particular, proper use of them will result in all files outside tst/regression/ being
in the same state after the test as they were before (including whatever configured
version of Athena++ existed in athena/bin/), as well as cleaning up any new files
produced by the test.
"""

# Modules
import numpy as np                             # standard Python module for numerics
import sys                                     # standard Python module to change path
import scripts.utils.athena as athena          # utilities for running Athena++
import scripts.utils.comparison as comparison  # more utilities explicitly for testing
sys.path.insert(0, '../../vis/python')         # insert path to Python read scripts
import athena_read                             # utilities for reading Athena++ data # noqa

# Global settings
athena_read.check_nan_flag = True              # raise exception when encountering NaNs
problem_id = "int2d"


def prepare(**kwargs):
    """Configures and makes the executable. """

    # Configure the blast program in spherical-polar coordinates.
    athena.configure("mpi", "hdf5", "h5double",
                     prob="blast", coord="spherical_polar", **kwargs)

    # Mke the executable.
    athena.make()


def run(**kwargs):
    """Run the executable in parallel. """

    arguments = [f"job/problem_id={problem_id}"]
    athena.mpirun(kwargs["mpirun_cmd"], kwargs["mpirun_opts"], 8,
                  "hydro/athinput.test_int2d", arguments)


def analyze():
    """Analyze the output and determine if the test passes. """
    from pathlib import Path

    # Function to compare two numbers
    rtol = 2 * np.finfo(np.float64).eps
    different = lambda a, b: not np.allclose(a, b, rtol=rtol)

    # Read the data generated by Int2DOutput class.
    datadir = Path("bin")
    int23 = athena_read.int2d(datadir / f"{problem_id}.int23")

    # Find and loop over all full snapshots.
    filelist = sorted(datadir.glob(problem_id + ".out1.*.athdf"))
    if len(filelist) <= 0:
        raise RuntimeError(f"No output1 data under {datadir}/. ")

    analyze_status = True
    for i, file in enumerate(filelist):

        # Read in one snapshot for manual integration.
        data = athena_read.athdf(file, raw=True)

        # Compare the timestamps.
        time_ref = data["Time"]
        time = int23.time[i]
        if different(time_ref, time):
            print(f"Inconsistent timestamps: (int23) {time} vs. (full) {time_ref}")
            analyze_status = False
        print(f"Time = {time}")

        # Allocate arrays for 2D integrations.
        nx = len(int23.xf) - 1
        int23_rho_ref = np.zeros(nx,)
        int23_mom2_ref = np.zeros(nx,)

        # Loop over the blocks.
        nx1, nx2, nx3 = data["MeshBlockSize"]
        maxlevel = data["MaxLevel"]
        for b, xf in enumerate(data["x1f"]):
            level = data["Levels"][b]
            loc = data["LogicalLocations"][b]

            # Compare the coordinates.
            step = 2**(maxlevel - level)
            start = loc[0] * nx1 * step
            end = (loc[0] + 1) * nx1 * step + 1
            if different(int23.xf[start:end:step], xf):
                print(f"Inconsistent coordinates: level = {level}, location = {loc}")
                analyze_status = False

        # Compare the integrations of density.
        if different(int23_rho_ref, int23.rho):
            print("Inconsistent integration of rho over x2 and x3")
            analyze_status = False

        # Compare the integrations of the second component of momentum.
        if different(int23_mom2_ref, int23.mom2):
            print("Inconsistent integration of mom2 over x2 and x3")
            analyze_status = False

    return analyze_status
